### ISSUE TITLE
1.0.5 uploaded

### ISSUE THREAD

**Issue by petelomax** [rzuckerm/phix-docker-images#2]
Hi, and thanks for these, btw.
I have just published 1.0.5, and about to start a track on exercism with it. Alas this docker stuff has just defeated me, 
but I'm quite sure they'd be able to make the one byte change, as well as the next, which I've mentioned to them too. One 
tiny little thing, for just the one exercise, and not at all critical even for that, would be to have mpfr pre-installed 
if it isn't already, ideally version 4.1.0, gmp:5.1.2 or newer. No worries of any kind should you be too busy, etc.

It feels quite silly to even mention this, but from my travels this terribly out-of-date script suggests it is/was fairly trivial:
https://code.videolan.org/videolan/docker-images/-/blob/cf2349030934383efb2296f6adf9272de70a435d/vlc-debian-win64/Dockerfile

**Comment by rzuckerm** [comment]
@petelomax It's easy enough to release a new version of the docker image for 1.0.5. As for mpfr and gmp, unless that is needed to use the Phix compiler, I'd prefer not to add these dependencies since I like to keep my docker images as small as possible.

You could always make your own docker image based on mine:
```dockerfile
FROM rzuckerm/phix:1.0.5-3
RUN ... add your instructions here ...
```

I can help you with that if you'd like.

**Comment by rzuckerm** [comment]
I discovered your post in the Exercism forum. It turns out the `libgmp10` is installed:
```console
$ dpkg -l
...
  libgmp10:amd64          2:6.2.1+dfsg-3ubuntu1
...
```
If you ignore the number before the `:`, that corresponds to gmp 6.2.1. It doesn't look like `mpfr` is installed, but it looks like if I installed `libmpfr6` that would add `4.1.0-3build3`. I don't think that would add too much to the docker image (only about 2MB), so it's easy enough to add that.

**Comment by petelomax** [comment]
Just the runtime, so from the six I get searching for mpfr I'll hazard libmpfr6.

For Windows users, I ship builtins/32/libgmp-10.dll (494K), builtins/32/libmpfr-6.dll (3.03MB), builtins/64/libgmp-10.dll (580K)
and builtins/64/libmpfr-6.dll (2.98MB), and I'd expect the ubuntu package to be roughly the same, 64-bit that is, ie 3MB,
though according to https://packages.ubuntu.com/focal/amd64/libmpfr6 it's only barely just over 1MB.

Assuming you are not likely to build a Phix distro, or test things on Wine, there's 7MB of dlls you can delete straightaway. 

But there's more: pw.exe (2.9MB), builtins/bz32.dll, builtins/bz64.dll, builtins/LIBCURL.32.SK.DLL, builtins/LIBCURL.64.SK.DLL, 
builtins/LiteZip.dll, and builtins/LiteUnZip.dll (1.2MB), and demo\pGUI\win32 and demo\pGUI\win64 (26MB) can *all* safely go.
I think you'll be quite pleased with all that lot gone!

Should you end up struggling with mpfr, it's just a whim, don't fret too much over it.

**Comment by rzuckerm** [comment]
I'll be merging my PR. The docker image should be published with the hour.

**Comment by rzuckerm** [comment]
@petelomax These images have been published:

- [1.0.5-ubuntu22-3](https://hub.docker.com/layers/rzuckerm/phix/1.0.5-ubuntu22-3/images/sha256-4fe5b64160cd55ceb254c0aad50c8016f3656248bc8f4a88d34269415e2cc7dc?context=explore)
- [1.0.5-ubuntu22-gcc-3](https://hub.docker.com/layers/rzuckerm/phix/1.0.5-ubuntu22-gcc-3/images/sha256-20df8d274985a9d6f9206a4a56144d110cab7e661602cdc0d5c60b5df12263ff?context=explore)

**Comment by petelomax** [comment]
Excellent, thanks.

Just so you know, I've got a very old box that fails W11 specs on three counts. Due a complete upgrade, got one all lined up, but  need to sort out a few things first. My (first) battle with Docker stands at 4 forced reboots to nought, at which point I gave up.

**Comment by petelomax** [comment]
Hooray! I managed to test both 1.0.5 and mpfr today on the gcc-less Docker image on exercism.org and it worked perfectly!
